version: "3.8"

services: 
    mysql:
        image: mysql
        restart: always
        ports: 
           - 3386:3306
        volumes: 
            - ./mysqldb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
        
    web:
        image: book-service
        ports: 
            - 8080:8080
        links: 
            - mysql